IF(NOT Exists(SELECT is_broker_enabled FROM sys.databases WHERE name = DB_NAME()))
BEGIN
	SET IMPLICIT_TRANSACTIONS OFF

	DECLARE @db varchar(max) = DB_NAME();

	Exec('ALTER DATABASE '+@db +' SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;');
	
	--ALTER DATABASE WizDb SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;

	SET IMPLICIT_TRANSACTIONS ON
END
